### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by lehitoskin** [cbowdon/gif-image#1]
@cbowdon I am interested in using this library for my own program, except it's kind of geared for the old PLaneT packaging system. I was going to do a reorganizing of the files and so forth to make it compatible with PLaneT2, perhaps even make some code changes if I find something that is different in the current version of Racket. That being said, I could make one really big PR, or if you're not interested in maintaining this library anymore I could become the active maintainer in your stead.

On another note, I don't seem to see any sort of license disclaimer anywhere in your source. Is there one in particular you'd like to have applied to this library?

**Comment by cbowdon** [comment]
Hi, apologies for the delayed reply. If you are still interested, please feel free to use this library under your choice of the MIT or GPLv3 license. I'd very much appreciate any size PR.

**Comment by lehitoskin** [comment]
Check out #2
